Repository silverlogic/baseapp-frontend, pull requests merged in 2025-03, with the labels that each got.

#221 BA-2267: generate edit username
  packages/components/.storybook/decorators/index.ts
  packages/components/.storybook/decorators/withMutationResolver.tsx
  packages/components/CHANGELOG.md
  packages/components/modules/messages/web/CreateChatRoomList/ChatRoomListItem/index.tsx
  packages/components/modules/profiles/common/constants.ts
  packages/components/modules/profiles/common/graphql/fragments/AllProfilesList.ts
  packages/components/modules/profiles/common/graphql/fragments/BlockToggle.ts
  packages/components/modules/profiles/common/graphql/fragments/FollowToggleUpdatableFragment.ts
  packages/components/modules/profiles/common/graphql/fragments/MemberItem.ts
  packages/components/modules/profiles/common/graphql/fragments/ProfileComponent.ts
  packages/components/modules/profiles/common/graphql/fragments/ProfileItem.ts
  packages/components/modules/profiles/common/graphql/fragments/ProfilesList.ts
  packages/components/modules/profiles/common/graphql/fragments/UserMembersList.ts
  packages/components/modules/profiles/common/graphql/queries/ProfileSettingsRelayTest.ts
  packages/components/modules/profiles/common/graphql/queries/ProfilesList.ts
  packages/components/modules/profiles/common/graphql/queries/UserMembersList.ts
  packages/components/modules/profiles/common/index.ts
  packages/components/modules/profiles/common/types.ts
  packages/components/modules/profiles/common/utils.ts
  packages/components/modules/profiles/common/zod.ts
  packages/components/modules/profiles/native/ProfileComponent/index.tsx
  packages/components/modules/profiles/native/ProfileSettingsComponent/index.tsx
  packages/components/modules/profiles/web/ProfileSettingsComponent/__storybook__/index.tsx
  packages/components/modules/profiles/web/ProfileSettingsComponent/__storybook__/mockResolver.ts
  packages/components/modules/profiles/web/ProfileSettingsComponent/__storybook__/stories.tsx
  packages/components/modules/profiles/web/ProfileSettingsComponent/index.tsx
  packages/components/modules/profiles/web/ProfileSettingsComponent/styled.tsx
  packages/components/modules/profiles/web/ProfileSettingsComponent/types.ts
  packages/components/modules/profiles/web/index.ts
  packages/components/modules/profiles/web/profile-popover/CurrentProfile/index.tsx
  packages/components/package.json
  packages/design-system/CHANGELOG.md
  packages/design-system/components/web/icons/UsernameIcon/index.tsx
  packages/design-system/components/web/icons/index.ts
  packages/design-system/components/web/inputs/PhoneNumberField/CountrySelect/index.tsx
  packages/design-system/components/web/inputs/PhoneNumberField/CountrySelect/styled.tsx
  packages/design-system/components/web/inputs/PhoneNumberField/__storybook__/PhoneNumberField.mdx
  packages/design-system/components/web/inputs/PhoneNumberField/__storybook__/stories.tsx
  packages/design-system/components/web/inputs/PhoneNumberField/constants.ts
  packages/design-system/components/web/inputs/PhoneNumberField/index.tsx
  packages/design-system/components/web/inputs/PhoneNumberField/styled.tsx
  packages/design-system/components/web/inputs/PhoneNumberField/types.ts
  packages/design-system/components/web/inputs/index.ts
  packages/design-system/package.json
  packages/wagtail/CHANGELOG.md
  packages/wagtail/package.json
  pnpm-lock.yaml
Labels: approved

#232 BA-2335: login and security page
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/design-system/CHANGELOG.md
  packages/design-system/components/native/icons/BiometricsIcon/index.tsx
  packages/design-system/components/native/icons/DevicesIcon/index.tsx
  packages/design-system/components/native/icons/EmailIcon/index.tsx
  packages/design-system/components/native/icons/KeyIcon/index.tsx
  packages/design-system/components/native/icons/LockIcon/index.tsx
  packages/design-system/components/native/icons/index.ts
  packages/design-system/package.json
  packages/wagtail/CHANGELOG.md
  packages/wagtail/package.json
Labels: needs review

#227 BA-2345-change-link-navigation-from-navbar
  packages/components/CHANGELOG.md
  packages/components/modules/navigations/web/Header/styled.tsx
  packages/components/modules/navigations/web/NavMini/NavSectionMini/NavList/NavItem/index.tsx
  packages/components/modules/navigations/web/__shared__/NavSectionHorizontal/NavList/NavItem/index.tsx
  packages/components/modules/navigations/web/__shared__/NavSectionHorizontal/NavList/NavItem/styled.tsx
  packages/components/modules/navigations/web/__shared__/NavSectionVertical/Group/NavList/NavItem/index.tsx
  packages/components/package.json
  pnpm-lock.yaml
Labels: needs review

#230 BA-1744: Technical Debts
  packages/components/CHANGELOG.md
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/CurrentProfileMenu/index.tsx
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/CurrentProfileMenu/types.ts
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/LogoutItem/index.tsx
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/LogoutItem/types.ts
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/__tests__/AccountPopover.cy.tsx
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/index.tsx
  packages/components/modules/navigations/web/Header/AccountMenu/AccountPopover/types.ts
  packages/components/package.json
Labels: needs review

#233 FEN-168 Make logo sx props customizable
  packages/components/CHANGELOG.md
  packages/components/modules/navigations/web/Header/index.tsx
  packages/components/modules/navigations/web/Header/types.ts
  packages/components/modules/navigations/web/NavMini/index.tsx
  packages/components/modules/navigations/web/NavMini/types.ts
  packages/components/modules/navigations/web/NavVertical/index.tsx
  packages/components/modules/navigations/web/NavVertical/types.ts
  packages/components/modules/navigations/web/NavigationLayout/index.tsx
  packages/components/modules/navigations/web/NavigationLayout/types.ts
  packages/components/package.json
  packages/design-system/components/web/logos/Logo/types.ts
Labels: needs changes

#236 BA-2357: Support first and last name during signup
  packages/authentication/CHANGELOG.md
  packages/authentication/modules/access/useSignUp/__tests__/useSignUp.test.tsx
  packages/authentication/modules/access/useSignUp/constants.ts
  packages/authentication/modules/access/useSignUp/index.ts
  packages/authentication/modules/access/useSignUp/types.ts
  packages/authentication/package.json
  packages/authentication/types/auth.ts
  packages/components/modules/navigations/web/__shared__/NavSectionHorizontal/NavList/NavItem/index.tsx
  packages/components/modules/navigations/web/__shared__/NavSectionHorizontal/NavList/NavItem/styled.tsx
Labels: needs changes

#212 BA-2234 Optimistic updates
  packages/components/CHANGELOG.md
  packages/components/modules/messages/common/graphql/mutations/SendMessage.ts
  packages/components/modules/messages/common/graphql/subscriptions/useMessagesListSubscription.tsx
  packages/components/modules/messages/web/MessagesList/index.tsx
  packages/components/modules/messages/web/SendMessage/index.tsx
  packages/components/package.json
  packages/components/schema.graphql
Labels: approved

#240 BA 2373 add Infinit scroller to notifications list and design system
  packages/components/CHANGELOG.md
  packages/components/modules/notifications/common/constants.ts
  packages/components/modules/notifications/common/types.ts
  packages/components/modules/notifications/native/NotificationsList/index.tsx
  packages/components/modules/notifications/native/NotificationsList/styles.ts
  packages/components/modules/notifications/web/NotificationsList/constants.ts
  packages/components/modules/notifications/web/NotificationsList/index.tsx
  packages/components/package.json
  packages/design-system/CHANGELOG.md
  packages/design-system/components/native/views/InfiniteScrollerView/index.tsx
  packages/design-system/components/native/views/InfiniteScrollerView/styles.ts
  packages/design-system/components/native/views/InfiniteScrollerView/types.ts
  packages/design-system/components/native/views/index.ts
  packages/design-system/package.json
  packages/wagtail/CHANGELOG.md
  packages/wagtail/package.json
  pnpm-lock.yaml
Labels: needs changes

#239 BA-2364: change password
  packages/authentication/CHANGELOG.md
  packages/authentication/modules/access/index.ts
  packages/authentication/modules/access/useChangePassword/__tests__/useChangePassword.test.tsx
  packages/authentication/modules/access/useChangePassword/constants.ts
  packages/authentication/modules/access/useChangePassword/index.ts
  packages/authentication/modules/access/useChangePassword/types.ts
  packages/authentication/package.json
  packages/authentication/services/auth.ts
  packages/authentication/types/auth.ts
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/design-system/CHANGELOG.md
  packages/design-system/components/native/buttons/Button/styles.ts
  packages/design-system/components/native/icons/AlertTriangleIcon/index.tsx
  packages/design-system/components/native/icons/index.ts
  packages/design-system/components/native/inputs/TextInput/index.tsx
  packages/design-system/components/native/inputs/TextInput/styles.ts
  packages/design-system/components/native/views/ScrollView/index.tsx
  packages/design-system/components/native/views/ScrollView/styles.ts
  packages/design-system/components/native/views/ScrollView/types.ts
  packages/design-system/components/native/views/index.ts
  packages/design-system/package.json
Labels: approved

#241 BA-2391: create native tabs component
  packages/components/__generated__/ActivityLogsFragment.graphql.ts
  packages/design-system/CHANGELOG.md
  packages/design-system/components/native/tabs/Tab/index.tsx
  packages/design-system/components/native/tabs/Tab/styles.ts
  packages/design-system/components/native/tabs/Tab/types.ts
  packages/design-system/components/native/tabs/Tabs/context.tsx
  packages/design-system/components/native/tabs/Tabs/index.tsx
  packages/design-system/components/native/tabs/Tabs/styles.ts
  packages/design-system/components/native/tabs/Tabs/types.ts
  packages/design-system/components/native/tabs/index.ts
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: needs review
